# Generated by Django on [Tu fecha o el nombre de tu migración]

from django.db import migrations

def create_initial_superuser(apps, schema_editor):
    User = apps.get_model('email', 'username')  # O el nombre de tu modelo de usuario personalizado

    # Usamos las variables de entorno de Render
    import os
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'Hakal')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'hakalsthrope@gmail.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'Tata11*')

    if not User.objects.filter(username=username).exists():
        # Crea el superusuario solo si no existe
        User.objects.create_superuser(
            username=username,
            email=email,
            password=password
        )

class Migration(migrations.Migration):

    dependencies = [
        # Coloca aquí la migración anterior, por ejemplo:
        ('tasks', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_initial_superuser),
    ]