# Generated by Django 5.2.7 on 2025-12-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_create_superuser'),
        ('tasks', '0005_professorfile'),
    ]

    operations = [
    ]
