# Generated by Django 5.2.7 on 2026-01-24 03:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_professorfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorfile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
